"""removed locaton in users and made filds for country state and city

Revision ID: 4ca668852e1a
Revises: 3038a6f7d60d
Create Date: 2026-05-09 12:59:34.944356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca668852e1a'
down_revision = '3038a6f7d60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state_province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('continent', sa.String(length=50), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('continent')
        batch_op.drop_column('country')
        batch_op.drop_column('state_province')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
